<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-D34DC2QJ" name="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest" tests="3" failures="0" timestamp="19 Feb 2021 16:44:22 GMT" time="10.256" errors="1">
  <testcase name="TC03_SuccessLoginTest" time="5.523" classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest"/>
  <testcase name="TC01_FailedLoginTest" time="3.550" classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest"/>
  <testcase name="TC02_FailedLoginTest" time="1.183" classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest">
    <error type="java.lang.AssertionError" message="Not matched expected [Invalid] but found [Invalid credentials]">
      <![CDATA[java.lang.AssertionError: Not matched expected [Invalid] but found [Invalid credentials]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest.TC02_FailedLoginTest(TC_LoginTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC02_FailedLoginTest -->
</testsuite> <!-- com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest -->
